# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0009_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='chat_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='group_id',
            new_name='resource_id',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='remind',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='teacher_id',
        ),
        migrations.AddField(
            model_name='chat',
            name='category',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('group', 'Group')], default='group', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chat',
            name='language',
            field=models.CharField(choices=[('ru', 'ru'), ('uk', 'uk')], default='ru', max_length=3),
        ),
    ]
