# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0010_auto_20160912_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='category',
            field=models.CharField(blank=True, choices=[('teacher', 'Teacher'), ('group', 'Group')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='resource_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
